### ISSUE TITLE
[FEATURE] - Update documentation (README) for v2 and v3 changes

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-whats-new#19]
### v2
- [x] `SponsorProvider`
- [x] `SocialMediaProvider`

### v3
- [x] Themeable image for `Sponsors`

**Comment by ryanraposo** [comment]
This is probably related to changes you're making, but the snippet is unclear/produces errors. I'm sure you're aware but let me know if you want any other input on it :)

**Comment by alefragnani** [comment]
Yes, these are related. The idea of this issue is exactly to update the snippets to be in sync with the latest API changes.
