### ISSUE TITLE
[FEATURE] Add information on how to use the submodule on your extension

### ISSUE THREAD

**Issue by DarkTrick** [alefragnani/vscode-whats-new#34]
# Feature Request:

Could you add detailed information on how to work on the extension? 

My first hurdle was to figure out, that `git clone` wouldn't clone the `whats-new` section. And even after that I couldn't get it to run

# Background / Details:

In regard of [this](https://github.com/alefragnani/vscode-separators/issues/21) issue, I thought, I'd look into your code base. But I have troubles debugging your extension. Apparently it has troubles finding the what's new section.

```
Activating extension 'alefragnani.separators' failed: Cannot find module '../../vscode-whats-new/src/Manager'.
```

**Comment by alefragnani** [comment]
Hi @DarkTrick ,

This repo is a **Git submodule**, so you must run the commands git provides to initialize them, after you cloned extension which uses this submodule.

It seems you tried to build the **Separators** extension. This extension (just like all my other extension) has no _special step_, other than those described in VS Code documentation/samples.

To sum up, after you cloned the **Separators** extension, you just have to run two additional commands:

```shell
    git submodule init
    git submodule update
```

Doing so, this **What’s New** submodule will be available on your file system.

Hope this helps
